spring:
   datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     password: 123456
     url: jdbc:mysql://localhost:3306/jpa
     username: root
   jpa:
     #开启SQL语句执行日志信息
      show-sql: true
      hibernate:
          #配置为自动创建
          ddl-auto: update  #create